site_name: data engineer
site_description: data engineer
site_author: Manisha
docs_dir: docs

# ======== mkdocs serve

nav:
  - Home: readme.md
  - Interview:
      - Behaviour:
          - 🔹00_behaviour: interview/behaviour/00_behaviour.md
          - 🔹01_Adaptability+Resilience : interview/behaviour/01_Adaptability+Resilience.md
          - 🔹02_SelfAware+Motivation: interview/behaviour/02_SelfAware&Motivation.md
          - 🔹03_TrustRelationship: interview/behaviour/03_TrustRelationship.md
          - 🔹04_teamwork: interview/behaviour/04_Teamwork & Collaboration.md
          - 🔹05_leadership: interview/behaviour/05_Leadership & Ownership.md
  - GenAI:
      - Learning:
          - 🔹2025: genAI/learning/2025.md
          - 🔹2024: genAI/learning/2024.md
      #- projects:




# ========

theme:
  name: material
  features:
    - navigation.tracking          # Enables breadcrumbs
    - navigation.tabs              # Optional: if using tabs layout
    - navigation.top               # Scroll-to-top button
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.footer            # Enables next/previous at bottom
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: pink
  custom_dir: .

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lekhrajdinkar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lekhraj-dinkar-25872140/